### ISSUE TITLE
[Bug?] Mails not sent if generated with PowerShell Core  unless you manually call "Invoke-MDDaemon"

### ISSUE THREAD

**Issue by Zerowalker** [PowershellFrameworkCollective/MailDaemon#5]
Currently it will only actually install for Windows PowerShell,
and any mail created from PowerShell Core will never be sent (learned this the hard way).

So in order for those mails to be sent Invoke-MDDaemon has to be called from PowerShell Core,
so it should create a task for that as well when you call "Install-MDDaemon" from Core.

Either that or perhaps "fix" so Windows PowerShell can send both?
Not sure how it's handled differently, I would expect them to end up in the same folders.

**Comment by FriedrichWeinmann** [comment]
Hi, thanks for finding this issue!
You are absolutely right, I messed up in remembering how I persist settings. The config system has several locations where it automatically looks for settings. Most notably: Registry, File System or Environment (multiple options each).
I forgot completely how the File System ones were PS Version specific, which is why the `Send-MDMail` call fails when called from a version other than the one you installed it for.

I'll fix that in the next version (and going to prioritize that version, so it'll be soon(tm)).
In the meantime, you can do an impromptu fix:

Run this on a console (as admin) that works correctly for the machine:

```powershell
Get-PSFConfig -FullName 'MailDaemon.Daemon.MailPickupPath' | Register-PSFConfig -Scope SystemDefault
```

This should unblock all consoles started on the machine henceforth (but not affect anything already running).

As mentioned, expect a new release soon - sometime this week - but I'll need some time to refactor the project to the new standard (the tests won't work anymore and need some refinements anyway). It will also require a new version of PSFramework, alas.

**Comment by FriedrichWeinmann** [comment]
Just release v1.0.0 - should now work as intended, for v5 and v7 equally

**Comment by Zerowalker** [comment]
Will have to try it out, i noticed that the bug appears when changing the default settings,
as they both grab it from different places.

Will close the issue as it should be fixed then, thanks:)
